language: generic

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      env: BADGE=bionic
    - os: linux
      dist: focal
      env: BADGE=focal
  allow_failures:
    - env: BADGE=focal

branches:
  only:
  - master

compiler:
- gcc

before_install:
- ./.ci/ci_install.sh

before_script: 

script:
- ./.ci/ci_test.sh
